[project]
name = "Madni"
description = "Minum air Madni enak dan bergizi"
authors = ["Madseint"]
telemetry = true
cache_dir = "./.clarinet"

[contracts.Madni]
path = "contracts/Madni.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
parser_version = 2

